import asyncio
import os
import shutil
import subprocess
from typing import Callable

# Resolve graphify binary — check common locations
def _find_graphify() -> str | None:
    candidates = [
        "/Library/Frameworks/Python.framework/Versions/3.12/bin/graphify",
        "/Library/Frameworks/Python.framework/Versions/3.11/bin/graphify",
        "/usr/local/bin/graphify",
        "/opt/homebrew/bin/graphify",
    ]
    # Also try PATH
    on_path = shutil.which("graphify")
    if on_path:
        return on_path
    for c in candidates:
        if os.path.isfile(c) and os.access(c, os.X_OK):
            return c
    return None


GRAPHIFY_BIN = _find_graphify()


class GraphifyRunner:
    @staticmethod
    async def run_graphify(project_path: str, emit_callback: Callable = None) -> bool:
        def emit(msg: str, event: str = "graphify"):
            if emit_callback:
                emit_callback({"event": event, "agent": "orchestrator", "message": msg})

        brain_dir = os.path.join(project_path, ".brain")
        os.makedirs(brain_dir, exist_ok=True)

        if not GRAPHIFY_BIN:
            emit("Graphify not found — generating basic Obsidian vault")
            GraphifyRunner._generate_basic_vault(project_path, brain_dir)
            return False

        try:
            emit(f"Running Graphify ({GRAPHIFY_BIN}) — building knowledge graph...")
            proc = await asyncio.create_subprocess_exec(
                GRAPHIFY_BIN, project_path,
                "--obsidian", f"--obsidian-dir={brain_dir}",
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )
            _, stderr = await asyncio.wait_for(proc.communicate(), timeout=120)

            if proc.returncode == 0:
                emit(f"Knowledge graph ready: {brain_dir}/graph.html", "graphify_complete")
                return True
            else:
                emit(f"Graphify failed: {stderr.decode()[:200]}")
                GraphifyRunner._generate_basic_vault(project_path, brain_dir)
                return False

        except asyncio.TimeoutError:
            emit("Graphify timed out — using fallback vault")
            GraphifyRunner._generate_basic_vault(project_path, brain_dir)
            return False

    @staticmethod
    def _generate_basic_vault(project_path: str, brain_dir: str):
        dirs = ["Architecture", "Components", "API", "Database", "Security"]
        for d in dirs:
            os.makedirs(os.path.join(brain_dir, d), exist_ok=True)

        index = f"""# Project Brain

> Auto-generated by OctoForge

## Sections

- [[Architecture/Overview|Architecture]]
- [[API/Index|API Routes]]
- [[Components/Index|Components]]
- [[Database/Index|Database]]
- [[Security/Index|Security]]

---
*Open this folder as an Obsidian vault to use graph view*
"""
        sections = {
            "00-Index.md": index,
            "Architecture/Overview.md": "# Architecture\n\nProject structure and tech decisions.\n",
            "API/Index.md": "# API Routes\n\nBackend endpoints.\n",
            "Components/Index.md": "# Components\n\nFrontend components.\n",
            "Database/Index.md": "# Database\n\nData models and schema.\n",
            "Security/Index.md": "# Security\n\nSecurity review notes.\n",
        }
        for name, content in sections.items():
            path = os.path.join(brain_dir, name)
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w") as f:
                f.write(content)
