class SetupGuideGenerator:
    @staticmethod
    def generate(project_path: str, project_name: str, dependencies: dict, file_structure: dict) -> str:
        backend_deps = dependencies.get("backend", {})
        frontend_deps = dependencies.get("frontend", {})
        has_python = bool(backend_deps)
        has_node = bool(frontend_deps)

        lines = [
            f"# {project_name.replace('-', ' ').title()} — Setup Guide",
            "",
            "> Generated by **OctoForge** — the multi-agent code forge",
            "",
            "## Prerequisites",
            "",
        ]
        if has_python:
            lines += ["- Python 3.10+", "- pip or uv"]
        if has_node:
            lines += ["- Node.js 18+", "- npm 9+"]
        lines += ["- Git", ""]

        if has_python:
            lines += [
                "## Backend Setup", "",
                "```bash",
                f"cd {project_path}",
                "",
                "# Create virtual environment",
                "python -m venv venv",
                "source venv/bin/activate  # Windows: venv\\Scripts\\activate",
                "",
                "# Install dependencies",
                "pip install -r requirements.txt",
                "```",
                "",
                "### Run Backend",
                "",
                "```bash",
                "source venv/bin/activate",
                "uvicorn main:app --reload --port 8000",
                "```",
                "",
                "API docs: http://localhost:8000/docs",
                "",
            ]

        if has_node:
            lines += [
                "## Frontend Setup", "",
                "```bash",
                "# Install dependencies",
                "npm install",
                "",
                "# Start dev server",
                "npm run dev",
                "```",
                "",
                "App: http://localhost:5173",
                "",
            ]

        lines += [
            "## Environment Variables",
            "",
            "Create `.env` in project root:",
            "",
            "```env",
            "DATABASE_URL=sqlite:///./app.db",
            "SECRET_KEY=change-this-in-production",
            "VITE_API_URL=http://localhost:8000",
            "```",
            "",
            "## Knowledge Graph",
            "",
            "Your project has an auto-generated Obsidian knowledge graph:",
            "",
            "```bash",
            f"open {project_path}/.brain/graph.html   # Interactive graph",
            f"# Or open {project_path}/.brain/ as an Obsidian vault",
            "```",
            "",
            "## Troubleshooting",
            "",
            "**Port in use:**",
            "```bash",
            "lsof -ti:8000 | xargs kill -9  # macOS/Linux",
            "```",
            "",
            "**Dependencies missing:**",
            "```bash",
            "pip install --force-reinstall -r requirements.txt",
            "npm ci",
            "```",
            "",
            "---",
            "",
            "*Built with ❤️ by OctoForge — open source at github.com/octoforge*",
        ]

        return "\n".join(lines)
